variable "region" {}
variable "project_name" {}
variable "vpc_cidr" {}
variable "public_sub_az1_cidr" {}
variable "public_sub_az2_cidr" {}
variable "private_app_sub_az1_cidr" {}
variable "private_app_sub_az2_cidr" {}
variable "private_data_subnet_az1" {}
variable "private_data_subnet_az2" {}
variable "key_name" {}
variable "instance_type" {}
variable "bastion_sgs" {} 
variable "public_subnets" {}
variable "frontend_app_sg" {}
variable "private_subnets" {}
variable "backend_app_sg" {}
variable "lb_tg" {}
